<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\PlanejamentoVooVisual.Core\PlanejamentoVooVisual.Core.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>app.ico</ApplicationIcon>
        <Version>1.2.0</Version>
        <AssemblyVersion>1.2.0.0</AssemblyVersion>
        <FileVersion>1.2.0.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
        <Resource Include="app.ico" />
    </ItemGroup>

</Project>
